"""Mirror drain-loop tuning knobs (shared across all channels)."""

from __future__ import annotations

from backend.config.telegram import (
    TELEGRAM_OUTBOX_BATCH_SIZE,
    TELEGRAM_OUTBOX_MAX_RETRIES,
    TELEGRAM_OUTBOX_POLL_SECONDS,
    TELEGRAM_OUTBOX_RETRY_SECONDS,
)

POLL_SECONDS = TELEGRAM_OUTBOX_POLL_SECONDS
BATCH_SIZE = TELEGRAM_OUTBOX_BATCH_SIZE
RETRY_SECONDS = TELEGRAM_OUTBOX_RETRY_SECONDS
MAX_RETRIES = TELEGRAM_OUTBOX_MAX_RETRIES
